### PR TITLE
Time region support

### LINKED ISSUE #10: Time Region Support
Hi, 

Firstly thanks, this is an amazing plugin thanks again for your hard work. 

-- Enhancement request--
I would like to see all hours on the heatmap for a given day,  however, I'd like to add Time Regions to highlight normal operating hours were I expect to see data. ie: 9am to 5pm.

Standard Graph with Time Regions:
Annotation 2020-09-07 113034

Same data in Hourly Heat Panel with additional time region added:
Annotation 2020-09-07 112443

It looks great, however, I'd like to add time region, current time,  a bonus feature, anything outside of the region changes red... 

Thanks!

### PR DESCRIPTION
**Pull request by marcusolsson**
Fixes #10

### CODE REVIEW

**Comment by marcusolsson** [comment]
Screen Shot 2020-09-11 at 15 04 30

**Comment by marcusolsson** [comment]
@securenotebook Would this work for you?

**Comment by securenotebook** [comment]
> @securenotebook Would this work for you?

WOW! looks amazing! Exactly what I wanted. Let me work out how to deploy this locally 

Thank you so much!

**Comment by marcusolsson** [comment]
Merging for now, but please let me know if you find any bugs or suggestions for improvement!

**Comment by securenotebook** [comment]
Hey marcusolsson, I'm trying to install this lastest master branch to test, however, I'm struggling...  Is there any easy way to do this? grafna-cli is only picking up version 0.5 latest version is 0.6. 

I git cloned the source and deployed in my docker container @ /var/lib/grafana/plugins/grafana-hourly-heatmap-panel/ then restarted grafana.

`t=2020-09-20T14:44:31+0800 lvl=warn msg="Plugin missing module.js" logger=plugins name="Hourly heatmap" warning="Missing module.js, If you loaded this plugin from git, make sure to compile it." path=/var/lib/grafana/plugins/grafana-hourly-heatmap-panel/src/module.js`

I've spent about an hour trying to work this out and failed. I thought I'd just ask the expert.

Or push to grafana plugins ?

**Comment by marcusolsson** [comment]
Hey! If you clone this from master, you need to build it before Grafana can load it. This should do it:

```
cd grafana-hourly-heatmap-panel
yarn install
yarn build
```

Then restart Grafana. Hope that works 👍

**Comment by securenotebook** [comment]
It was staring me right in the face!  When i tried to run yarn it wasnt installed so i moved on.... after installing it all good. 

First glance, everything is working as expected! 

You are a superstar! Thanks!

**Pull request merged**
